Update export_releases.yml

diff --git a/.github/workflows/export_releases.yml b/.github/workflows/export_releases.yml
--- a/.github/workflows/export_releases.yml
+++ b/.github/workflows/export_releases.yml
@@ -22,8 +22,8 @@ jobs:
     runs-on: ubuntu-latest
     permissions:
       contents: write
-    # outputs:
-    #   new_version_code: ${{ steps.prev_version.outputs.new_code }}  # Add this to share the output for the release
+    outputs:
+      new_version_code: ${{ steps.prev_version.outputs.new_code }}  # Add this to share the output for the release
     steps:
       - uses: actions/checkout@v4
         with:
@@ -37,53 +37,53 @@ jobs:
           exit 1
           fi
 
-      # - name: Get Previous Version Code
-      #   id: prev_version
-      #   run: |
-      #     PREV_CODE=$(grep -o 'version/code=[0-9]*' export_presets.cfg | head -1 | cut -d= -f2)
-      #     NEW_CODE=$((PREV_CODE + 10))
-      #     echo "prev_code=${PREV_CODE}" >> $GITHUB_OUTPUT
-      #     echo "new_code=${NEW_CODE}" >> $GITHUB_OUTPUT
+      - name: Get Previous Version Code
+        id: prev_version
+        run: |
+          PREV_CODE=$(grep -o 'version/code=[0-9]*' export_presets.cfg | head -1 | cut -d= -f2)
+          NEW_CODE=$((PREV_CODE + 10))
+          echo "prev_code=${PREV_CODE}" >> $GITHUB_OUTPUT
+          echo "new_code=${NEW_CODE}" >> $GITHUB_OUTPUT
 
-      # - name: Check Existing Version Code
-      #   run: |
-      #     if [ -f "./fastlane/metadata/android/en-US/changelogs/${{ steps.prev_version.outputs.new_code }}.txt" ]; then
-      #       echo "Error: Version code ${{ steps.prev_version.outputs.new_code }} already exists in metadata"
-      #       exit 1
-      #     fi
+      - name: Check Existing Version Code
+        run: |
+          if [ -f "./fastlane/metadata/android/en-US/changelogs/${{ steps.prev_version.outputs.new_code }}.txt" ]; then
+            echo "Error: Version code ${{ steps.prev_version.outputs.new_code }} already exists in metadata"
+            exit 1
+          fi
 
-      # - name: Extract Changelog
-      #   run: |
-      #     mkdir -p ./fastlane/metadata/android/en-US/changelogs
-      #     sed -n "/## v${{ inputs.version_name }}/,/## v/p" CHANGELOG.md | \
-      #     sed '$d' | sed '1s/^## //' > \
-      #     "./fastlane/metadata/android/en-US/changelogs/${{ steps.prev_version.outputs.new_code }}.txt"
+      - name: Extract Changelog
+        run: |
+          mkdir -p ./fastlane/metadata/android/en-US/changelogs
+          sed -n "/## v${{ inputs.version_name }}/,/## v/p" CHANGELOG.md | \
+          sed '$d' | sed '1s/^## //' > \
+          "./fastlane/metadata/android/en-US/changelogs/${{ steps.prev_version.outputs.new_code }}.txt"
           
       
       
-      # - name: Commit Previous Version Code
-      #   run: |
-      #     echo "Previous version code: ${{ steps.prev_version.outputs.prev_code }}"
-      #     echo "New version code: ${{ steps.prev_version.outputs.new_code }}"
+      - name: Commit Previous Version Code
+        run: |
+          echo "Previous version code: ${{ steps.prev_version.outputs.prev_code }}"
+          echo "New version code: ${{ steps.prev_version.outputs.new_code }}"
           
-      #     VERSION_CODE=${{ steps.prev_version.outputs.new_code }}
+          VERSION_CODE=${{ steps.prev_version.outputs.new_code }}
           
-      #     sed -i "/version\/name=\".*\"/s//version\/name=\"${{ inputs.version_name }}\"/" export_presets.cfg
+          sed -i "/version\/name=\".*\"/s//version\/name=\"${{ inputs.version_name }}\"/" export_presets.cfg
           
-      #     # Update version codes
-      #     sed -i "0,/version\/code=[0-9]*/s//version\/code=$VERSION_CODE/" export_presets.cfg
-      #     sed -i "0,/version\/code=[0-9]*/! {0,/version\/code=[0-9]*/s//version\/code=$((VERSION_CODE+1))/}" export_presets.cfg
-      #     sed -i "$(grep -n 'version/code=' export_presets.cfg | tail -n1 | cut -d: -f1),\$s/version\/code=[0-9]*/version\/code=$((VERSION_CODE+2))/" export_presets.cfg
+          # Update version codes
+          sed -i "0,/version\/code=[0-9]*/s//version\/code=$VERSION_CODE/" export_presets.cfg
+          sed -i "0,/version\/code=[0-9]*/! {0,/version\/code=[0-9]*/s//version\/code=$((VERSION_CODE+1))/}" export_presets.cfg
+          sed -i "$(grep -n 'version/code=' export_presets.cfg | tail -n1 | cut -d: -f1),\$s/version\/code=[0-9]*/version\/code=$((VERSION_CODE+2))/" export_presets.cfg
 
-      # - name: Commit Changes
-      #   run: |
-      #     git config --local user.email "action@github.com"
-      #     git config --local user.name "GitHub Actions"
-      #     git pull
-      #     git add export_presets.cfg
-      #     git add ./fastlane/metadata/android/en-US/changelogs/${{ steps.prev_version.outputs.new_code }}.txt
-      #     git commit -m "Update version to ${{ inputs.version_name }} (${{ steps.prev_version.outputs.new_code }})"
-      #     git push
+      - name: Commit Changes
+        run: |
+          git config --local user.email "action@github.com"
+          git config --local user.name "GitHub Actions"
+          git pull
+          git add export_presets.cfg
+          git add ./fastlane/metadata/android/en-US/changelogs/${{ steps.prev_version.outputs.new_code }}.txt
+          git commit -m "Update version to ${{ inputs.version_name }} (${{ steps.prev_version.outputs.new_code }})"
+          git push
       
 
   prepare-and-build:
@@ -137,6 +137,6 @@ jobs:
           files: ${{ github.workspace }}/builds/*
           name: ${{ inputs.version_name }}
           tag_name: ${{ inputs.version_name }}
-          # body_path: ./fastlane/metadata/android/en-US/changelogs/${{ needs.commit-vercode-changes.outputs.new_version_code }}.txt
+          body_path: ./fastlane/metadata/android/en-US/changelogs/${{ needs.commit-vercode-changes.outputs.new_version_code }}.txt
           prerelease: ${{ inputs.mark_prerelease }}
           generate_release_notes: true
